[workspace]
channels = ["conda-forge", "pypi"]
platforms = ["linux-64"]
preview = ["pixi-build"]
name = "ghs"
version = "0.1.0"
authors = ["zuble <67658465+zuble@users.noreply.github.com>"]

[tasks]
main="python src/ghs/main.py"

[dependencies]

[pypi-dependencies]
ghs = { path = ".", editable = true }
# inquirerpy = { git = "https://github.com/zuble/InquirerPy.git", rev = "master" }



[package]
name = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
# description = { workspace = true }
# documentation = { workspace = true }
# homepage = { workspace = true }
# license = { workspace = true }
# license-file = { workspace = true }
# readme = { workspace = true }
# repository = { workspace = true }

[package.build]
backend = { name = "pixi-build-python", version = "*" }

# [package.build.config]
# ignore-pypi-mapping = true

[package.host-dependencies]
hatchling = "*"
uv = "*"
