[workspace]
authors = ["zuble <67658465+zuble@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ghs2"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
main="python main.py"

[dependencies]
python = ">=3.14.2,<3.15"

[pypi-dependencies]
inquirerpy = { git = "https://github.com/zuble/InquirerPy.git", rev = "828d9b7" } 
bs4 = ">=0.0.2, <0.0.3"
pyrootutils = ">=1.0.4, <2"
requests = ">=2.32.5, <3"
rich = ">=14.2.0, <15"
click = ">=8.3.1, <9"
